-- Tabela para armazenar logs de aprendizado da IA (Feedback Loop)
CREATE TABLE IF NOT EXISTS public.classificacao_feedback (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    sugestao_ia text,
    escolha_real text,
    contexto_resumido text -- Snippet da conversa para análise
);

-- Habilita RLS (Opcional, mas boa prática)
ALTER TABLE public.classificacao_feedback ENABLE ROW LEVEL SECURITY;

-- Permite inserção pública (Backend/Anon key se necessário, mas backend usa service role)
-- Política para permitir leitura apenas por admins (se houver auth)
